name: CI/CD Pipeline for sitemate-backend-challenge-issue-tracker

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sitemate-backend-isuue-tracker .
          docker push ${{ secrets.DOCKER_USERNAME }}/sitemate-backend-isuue-tracker

      - name: Build and push frontend image
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sitemate-frontend-isuue-tracker .
          docker push ${{ secrets.DOCKER_USERNAME }}/sitemate-frontend-isuue-tracker
